name: terraform-fmt-check
description: Check that Terraform configuration files are in canonical format
author: Daniel Flook

inputs:
  path:
    description: Path to the terraform configuration
    required: true

runs:
  using: docker
  image: docker://danielflook/terraform-github-actions:v1.9.0
  entrypoint: /entrypoints/fmt-check.sh

branding:
  icon: globe
  color: purple
