name: terraform-fmt-check
description: Check that Terraform configuration files are in canonical format
author: Daniel Flook

inputs:
  path:
    description: Path to the terraform configuration
    required: false
    default: .

runs:
  using: docker
  image: docker://danielflook/terraform-github-actions@sha256:7340e0fda478b550b89feaa389a4397946e29a841f86ac39397a771ba205e06e
  entrypoint: /entrypoints/fmt-check.sh

branding:
  icon: globe
  color: purple
