name: terraform-fmt-check
description: Check that Terraform configuration files are in canonical format
author: Daniel Flook

inputs:
  path:
    description: Path to the terraform configuration
    required: false
    default: .

runs:
  using: docker
  image: docker://danielflook/terraform-github-actions@sha256:07cd443fbd4fc64bddf6901cfb1e6daff9f4b3935e68324bf40d395fb2ad6a7f
  entrypoint: /entrypoints/fmt-check.sh

branding:
  icon: globe
  color: purple
